### ISSUE TITLE
kill Node Red container when Internet fall

### ISSUE THREAD

**Issue by MuadDibVV** [tvecera/node-red-contrib-netatmo-energy#12]
Hello,
I suspect this node to induce an error (not catchable) on my node red container when the internet connection is down. Is it possible to correct that ?

19 Oct 21:48:17 - [error] - [-1] - Authenticate refresh error: No response
19 Oct 21:48:17 - [red] Uncaught Exception:
19 Oct 21:48:17 - [error] TypeError: Cannot read properties of undefined (reading 'statusCode')
    at Netatmo.handleRequestError (/data/node_modules/node-red-contrib-netatmo-energy/src/netatmo-energy-api.js:180:22)
    at Netatmo.<anonymous> (/data/node_modules/node-red-contrib-netatmo-energy/src/netatmo-energy-api.js:120:29)
    at self.callback (/data/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.onRequestError (/data/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by tvecera** [comment]
Fixed in version 0.9.2. Please try.

**Comment by MuadDibVV** [comment]
Thanks a lot !
